apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        - name: mongo-config
          mountPath: /etc/mongo
          subPath: mongo.conf
        - name: mongo-logs
          mountPath: /var/lib/logs
        command: ["mongod", "--config", "/etc/mongo/mongo.conf"]
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-config
        configMap:
          name: mongo-config
      - name: mongo-logs
        persistentVolumeClaim:
          claimName: mongo-logs-pvc