apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo.conf: |
    # Example MongoDB configuration file
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /var/lib/logs/mongodb.log
      logAppend: true
    net:
      bindIp: 0.0.0.0
      port: 27017